openapi: 3.2.0
info:
  description: Daytona Toolbox API
  title: Daytona Sandbox Toolbox Server API
  contact: {}
  license:
    name: Apache-2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  version: v0.0.0-dev
servers:
- url: https://proxy.app.daytona.io/toolbox
  description: Daytona Sandbox Toolbox proxy
tags:
- name: server
paths:
  /init:
    post:
      description: Set the auth token and initialize telemetry for the toolbox server
      tags:
      - server
      summary: Initialize toolbox server
      operationId: Initialize
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InitializeRequest'
        description: Initialization request
        required: true
components:
  schemas:
    InitializeRequest:
      type: object
      required:
      - token
      properties:
        token:
          type: string
